#!/bin/bash

# Collect dynamic data

hostname=$(hostname)
username=$(whoami)
datetime=$(date '+%Y-%m-%d %H:%M:%S')

# OS info: distro name and version
# Using /etc/os-release source to get pretty name
source /etc/os-release
os="$NAME $VERSION"

# Uptime info
uptime_info=$(uptime -p)

# CPU info: processor make and model
cpu=$(sudo lshw -class processor 2>/dev/null | grep "product" | head -n1 | cut -d: -f2 | xargs)

# RAM info: installed RAM size
ram=$(sudo lshw -class memory 2>/dev/null | grep -A1 "System Memory" | grep "size" | head -n1 | cut -d: -f2 | xargs)

# Disk info: make, model, size for all installed disks
disk=$(sudo lshw -class disk 2>/dev/null | grep -E "product|size" | sed 'N;s/\n/ /' | awk -F': ' '{print $2}' | paste -sd ", " -)

# Video card info: make and model
video=$(sudo lshw -class display 2>/dev/null | grep "product" | head -n1 | cut -d: -f2 | xargs)

# IP address for interface connected to default gateway
host_address=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K\S+')

# Gateway IP
gateway=$(ip route | grep default | awk '{print $3}')

# DNS server IP (first one listed)
dns=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n1)

# Users logged in
users=$(who | awk '{print $1}' | sort -u | paste -sd "," -)

# Disk free space for local filesystems: format "/mountpoint N"
disk_space=$(df -h --output=target,avail | tail -n +2 | awk '{print $1, $2}' | paste -sd "," -)

# Process count
process_count=$(ps -e --no-headers | wc -l)

# Load averages (1,5,15 min)
load_avg=$(uptime | awk -F'load average:' '{print $2}' | xargs)

# Listening network ports
listening_ports=$(ss -tuln 2>/dev/null | grep LISTEN | awk '{print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd "," -)

# UFW status
ufw_status=$(sudo ufw status 2>/dev/null | head -n1)

# Output report with blank lines before and after
cat << EOF

System Report for $hostname generated by $username, on $datetime

System Information
------------------
OS: $os
Uptime: $uptime_info
CPU: $cpu
RAM: $ram
Disk(s): $disk
Video: $video
Host Address: $host_address
Gateway IP: $gateway
DNS Server: $dns

System Status
-------------
Users Logged In: $users
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_avg
Listening Network Ports: $listening_ports
UFW Status: $ufw_status

EOF


